name: pillbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  showcaseview: ^5.0.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  flutter_typeahead: ^5.2.0
  timezone: ^0.10.1
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.5.0
  android_alarm_manager_plus: ^5.0.0
  mobile_scanner: ^3.5.7
  wifi_iot: ^0.3.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
